import { describe,expect,it } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const root=join(process.cwd(),"deployment","windows");
const read=(name:string)=>readFileSync(join(root,name),"utf8");

describe("Windows production deployment",()=>{
  it("registers non-interactive startup and verified backup tasks",()=>{const script=read("Install-CreatorOS.ps1");expect(script).toContain('New-ScheduledTaskTrigger -AtStartup');expect(script).toContain('-UserId "SYSTEM"');expect(script).toContain('TaskName "CreatorOS-Backup"');expect(script).toContain('WindowStyle Hidden');expect(script).toContain('Invoke-CreatorOSTaskAndWait')});
  it("preserves creator data when background tasks are removed",()=>{const script=read("Uninstall-CreatorOSService.ps1");expect(script).not.toMatch(/Remove-Item.+(?:DataRoot|attachments|backups|\.env)/i);expect(script).toContain("were preserved")});
  it("requires an explicit test database for restore verification",()=>{const script=read("Restore-Test-CreatorOS.ps1");expect(script).toContain('[Parameter(Mandatory)][string]$TestDatabaseUrl');expect(script).not.toContain('DATABASE_URL = $settings')});
  it("refuses long-lived bootstrap credentials",()=>expect(read("Install-CreatorOS.ps1")).toContain('Remove OWNER_EMAIL, OWNER_DISPLAY_NAME, and OWNER_PASSWORD'));
  it("supports the project Node engine and discovers standard PostgreSQL tools",()=>{expect(read("Install-CreatorOS.ps1")).toContain('$major -lt 22');expect(read("CreatorOS.Common.ps1")).toContain('PostgreSQL\\*\\bin')});
  it("loads server settings for migration commands without printing them",()=>{const common=read("CreatorOS.Common.ps1"),installer=read("Install-CreatorOS.ps1");expect(common).toContain('SetEnvironmentVariable');expect(common).toContain('"Process"');expect(installer).toContain('Import-CreatorOSEnvironment');expect(installer).not.toContain('Write-Host $settings')});
  it("stops an existing app before replacing locked dependencies and restores it on failure",()=>{const script=read("Install-CreatorOS.ps1"),stop=script.indexOf("Stop-CreatorOSApp"),install=script.indexOf('Invoke-CreatorOSCommand $npm @("ci"');expect(stop).toBeGreaterThan(0);expect(stop).toBeLessThan(install);expect(script).toContain('if ($existingAppWasRunning) { Start-ScheduledTask')});
  it("tracks and terminates only the Creator OS child process",()=>{const runner=read("Run-CreatorOS.ps1"),common=read("CreatorOS.Common.ps1");expect(runner).toContain('"app.pid"');expect(common).toContain('function Stop-CreatorOSApp');expect(common).toContain('CommandLine.Contains($AppRoot)');expect(common).toContain('CommandLine.Contains("node_modules\\next")');expect(common).not.toContain('Stop-Process -Name node')});
  it("waits for the newly requested backup run instead of reading a stale result",()=>{const common=read("CreatorOS.Common.ps1"),installer=read("Install-CreatorOS.ps1");expect(common).toContain('function Invoke-CreatorOSTaskAndWait');expect(common).toContain('$info.LastRunTime -gt $before');expect(installer).toContain('Invoke-CreatorOSTaskAndWait "CreatorOS-Backup"')});
  it("allows SYSTEM to record the backup revision and logs hidden backup failures",()=>{const script=read("Backup-CreatorOS.ps1");expect(script).toContain('safe.directory=$AppRoot');expect(script).toContain('backup-latest.log');expect(script).toContain('Start-Transcript')});
  it("resolves the restore app root after script initialization",()=>{const script=read("Restore-Test-CreatorOS.ps1");expect(script).toContain('if (-not $AppRoot)');expect(script).toContain('Resolve-Path (Join-Path $PSScriptRoot "..\\..")')});
  it("places the icon outside the protected data root and creates an internet shortcut",()=>{const script=read("Install-CreatorOS.ps1");expect(script).toContain('Pictures\\Creator OS');expect(script).toContain('CreatorOS-v5.ico');expect(script).toContain('Creator OS.url');expect(script).toContain('[InternetShortcut]');expect(script).not.toContain('Join-Path $DataRoot "CreatorOS-v5.ico"')});
  it("recreates the public internet shortcut during updates",()=>{const script=read("Update-CreatorOS.ps1");expect(script).toContain('Pictures\\Creator OS');expect(script).toContain('CreatorOS-v5.ico');expect(script).toContain('Creator OS.url');expect(script).toContain('IconFile=$iconPath');expect(script).toContain('Remove-Item -LiteralPath $legacyShortcutPath')});
  it("ships a standard PNG-compressed multi-size Windows icon",()=>{const icon=Buffer.from(read("CreatorOS.ico.b64"),"base64");expect([...icon.subarray(0,6)]).toEqual([0,0,1,0,7,0]);expect(icon[6]).toBe(16);expect(icon[22]).toBe(24);expect(icon[38]).toBe(32);const firstOffset=icon.readUInt32LE(18);expect([...icon.subarray(firstOffset,firstOffset+8)]).toEqual([137,80,78,71,13,10,26,10])});
});
