"use server";
import{redirect}from"next/navigation";import{revalidatePath}from"next/cache";import{z}from"zod";import{requireOwner}from"@/lib/auth/server";import{dateInputToUtc}from"@/lib/calendar/dates";import{permanentlyDeletePublication,reschedulePublication,scheduleFilm,schedulePublication}from"@/lib/calendar/repository";
const scheduleFilmInput=z.object({contentId:z.string().uuid(),date:z.string().date()});
const schedulePublicationInput=scheduleFilmInput.extend({accountId:z.string().uuid()});
const moveInput=z.object({publicationId:z.string().uuid(),date:z.string().date()});
const invalid=(message:string):never=>redirect(`/calendar?error=${encodeURIComponent(message)}`);
export async function scheduleFilmAction(form:FormData){const owner=await requireOwner(),result=scheduleFilmInput.safeParse({contentId:form.get("contentId"),date:form.get("date")});if(!result.success)return invalid("Choose content and a filming date first.");if(!await scheduleFilm(owner.id,result.data.contentId,dateInputToUtc(result.data.date)))return invalid("That content is no longer available.");revalidatePath("/calendar");redirect("/calendar?saved=film")}
export async function schedulePublicationAction(form:FormData){const owner=await requireOwner(),result=schedulePublicationInput.safeParse({contentId:form.get("contentId"),accountId:form.get("accountId"),date:form.get("date")});if(!result.success)return invalid("Choose content, an account, and a publication date first.");if(!await schedulePublication(owner.id,result.data.contentId,result.data.accountId,dateInputToUtc(result.data.date)))return invalid("That content or platform account is no longer available.");revalidatePath("/calendar");redirect("/calendar?saved=publication")}
export async function reschedulePublicationAction(form:FormData){const owner=await requireOwner(),result=moveInput.safeParse({publicationId:form.get("publicationId"),date:form.get("date")});if(!result.success)return invalid("Choose a valid publication date.");await reschedulePublication(owner.id,result.data.publicationId,dateInputToUtc(result.data.date));revalidatePath("/calendar")}
export async function permanentlyDeletePublicationAction(form:FormData){const owner=await requireOwner(),publicationId=z.string().uuid().safeParse(form.get("publicationId"));if(!publicationId.success||!await permanentlyDeletePublication(owner.id,publicationId.data))invalid("Published history is protected.");revalidatePath("/calendar")}
