"use server";
import { redirect } from "next/navigation";import { revalidatePath } from "next/cache";import { requireOwner } from "@/lib/auth/server";
import { createProductSchema, listingSchema, productEditSchema, quickSampleSchema, sampleEditSchema, sampleTransitionSchema } from "@/lib/samples/contracts";
import { addListing, archiveProduct, createProduct, createQuickSample, recoverProduct, transitionSample, updateProduct, updateSample } from "@/lib/samples/repository";
const v=(f:FormData,n:string)=>f.get(n);
export async function createSampleAction(f:FormData){const o=await requireOwner();const id=await createQuickSample(o.id,quickSampleSchema.parse({productId:v(f,"productId"),newProductName:v(f,"newProductName"),sourcePlatform:v(f,"sourcePlatform")}));redirect(`/products/samples/${id}`);}
export async function createProductAction(f:FormData){const o=await requireOwner();const id=await createProduct(o.id,createProductSchema.parse({name:v(f,"name")}));redirect(`/products/${id}`);}
export async function updateProductAction(f:FormData){const o=await requireOwner();const x=productEditSchema.parse({productId:v(f,"productId"),name:v(f,"name"),category:v(f,"category"),notes:v(f,"notes"),active:v(f,"active")});await updateProduct(o.id,x);revalidatePath(`/products/${x.productId}`);}
export async function addListingAction(f:FormData){const o=await requireOwner();const x=listingSchema.parse({productId:v(f,"productId"),platform:v(f,"platform"),externalProductId:v(f,"externalProductId"),externalUrl:v(f,"externalUrl"),affiliateUrl:v(f,"affiliateUrl")});await addListing(o.id,x);revalidatePath(`/products/${x.productId}`);}
export async function updateSampleAction(f:FormData){const o=await requireOwner();const x=sampleEditSchema.parse({sampleId:v(f,"sampleId"),sourcePlatform:v(f,"sourcePlatform"),expectedDeliveryAt:v(f,"expectedDeliveryAt"),trackingReference:v(f,"trackingReference"),contentId:v(f,"contentId"),campaignId:v(f,"campaignId"),notes:v(f,"notes")});await updateSample(o.id,x);revalidatePath(`/products/samples/${x.sampleId}`);}
export async function transitionSampleAction(f:FormData){const o=await requireOwner();const x=sampleTransitionSchema.parse({sampleId:v(f,"sampleId"),to:v(f,"to")});if(!await transitionSample(o.id,x.sampleId,x.to))throw new Error("Invalid sample transition");revalidatePath("/products");revalidatePath(`/products/samples/${x.sampleId}`);}
export async function archiveProductAction(f:FormData){const o=await requireOwner();await archiveProduct(o.id,String(v(f,"productId")));revalidatePath("/products");redirect("/products");}
export async function recoverProductAction(f:FormData){const o=await requireOwner();await recoverProduct(o.id,String(v(f,"productId")));revalidatePath("/products");}
