"use server";
import { redirect } from "next/navigation";import { revalidatePath } from "next/cache";import { requireOwner } from "@/lib/auth/server";
import { createProductSchema, listingSchema, productEditSchema, quickSampleSchema, sampleEditSchema, sampleTransitionSchema } from "@/lib/samples/contracts";
import { addListing, archiveProduct, archiveSample, createProduct, createQuickSample, permanentlyDeleteProduct, permanentlyDeleteSample, recoverProduct, recoverSample, transitionSample, updateProduct, updateSample } from "@/lib/samples/repository";
import { duplicateToken,duplicateWarningUrl,findDuplicates,findSampleDuplicates,validDuplicateToken } from "@/lib/duplicates/server";
const v=(f:FormData,n:string)=>f.get(n);
export async function createSampleAction(f:FormData){const o=await requireOwner(),raw={productId:String(v(f,"productId")??""),newProductName:String(v(f,"newProductName")??""),sourcePlatform:String(v(f,"sourcePlatform")??"")},result=quickSampleSchema.safeParse(raw);if(!result.success){const query=new URLSearchParams({sampleError:result.error.issues[0]?.message??"Check the sample details.",...raw});redirect(`/products?${query}`)}const signature=`${result.data.productId||result.data.newProductName}\0${result.data.sourcePlatform}`,matches=await findSampleDuplicates(o.id,result.data.productId??undefined,result.data.newProductName??undefined,result.data.sourcePlatform??"");if(matches.length&&!validDuplicateToken(String(f.get("duplicateToken")||""),o.id,"product",signature))redirect(duplicateWarningUrl("/products",{duplicateFlow:"sample",...raw},duplicateToken(o.id,"product",signature),matches));const id=await createQuickSample(o.id,result.data);redirect(`/products/samples/${id}`);}
export async function createProductAction(f:FormData){const o=await requireOwner(),input=createProductSchema.parse({name:v(f,"name")}),matches=await findDuplicates(o.id,"product",input.name);if(matches.length&&!validDuplicateToken(String(f.get("duplicateToken")||""),o.id,"product",input.name))redirect(duplicateWarningUrl("/products",{name:input.name},duplicateToken(o.id,"product",input.name),matches));const id=await createProduct(o.id,input);redirect(`/products/${id}`);}
export async function updateProductAction(f:FormData){const o=await requireOwner();const x=productEditSchema.parse({productId:v(f,"productId"),name:v(f,"name"),category:v(f,"category"),notes:v(f,"notes"),active:v(f,"active")});await updateProduct(o.id,x);revalidatePath(`/products/${x.productId}`);}
export async function addListingAction(f:FormData){const o=await requireOwner();const x=listingSchema.parse({productId:v(f,"productId"),platform:v(f,"platform"),externalProductId:v(f,"externalProductId"),externalUrl:v(f,"externalUrl"),affiliateUrl:v(f,"affiliateUrl")});await addListing(o.id,x);revalidatePath(`/products/${x.productId}`);}
export async function updateSampleAction(f:FormData){const o=await requireOwner();const x=sampleEditSchema.parse({sampleId:v(f,"sampleId"),sourcePlatform:v(f,"sourcePlatform"),expectedDeliveryAt:v(f,"expectedDeliveryAt"),trackingReference:v(f,"trackingReference"),contentId:v(f,"contentId"),campaignId:v(f,"campaignId"),notes:v(f,"notes")});await updateSample(o.id,x);revalidatePath(`/products/samples/${x.sampleId}`);}
export async function transitionSampleAction(f:FormData){const o=await requireOwner();const x=sampleTransitionSchema.parse({sampleId:v(f,"sampleId"),to:v(f,"to")});if(!await transitionSample(o.id,x.sampleId,x.to))throw new Error("Invalid sample transition");revalidatePath("/products");revalidatePath(`/products/samples/${x.sampleId}`);}
export async function archiveProductAction(f:FormData){const o=await requireOwner();await archiveProduct(o.id,String(v(f,"productId")));revalidatePath("/products");redirect(f.get("returnTo")==="list"?"/products?archivedProduct=1":"/products");}
export async function recoverProductAction(f:FormData){const o=await requireOwner();await recoverProduct(o.id,String(v(f,"productId")));revalidatePath("/products");}
export async function archiveSampleAction(f:FormData){const o=await requireOwner();await archiveSample(o.id,String(v(f,"sampleId")));revalidatePath("/products");redirect("/products?sampleArchived=1");}
export async function recoverSampleAction(f:FormData){const o=await requireOwner();await recoverSample(o.id,String(v(f,"sampleId")));revalidatePath("/products");redirect("/products?archivedSamples=1&sampleRecovered=1");}
export async function permanentlyDeleteProductAction(f:FormData){const o=await requireOwner(),id=String(v(f,"productId"));if(!await permanentlyDeleteProduct(o.id,id))redirect(`/products/${id}?deleteError=Remove%20samples%2C%20listings%2C%20content%20links%2C%20and%20PDFs%20first.`);revalidatePath("/products");redirect("/products?deleted=1");}
export async function permanentlyDeleteSampleAction(f:FormData){const o=await requireOwner(),id=String(v(f,"sampleId"));if(!await permanentlyDeleteSample(o.id,id))redirect(`/products/samples/${id}?deleteError=Remove%20PDF%20attachments%20first.`);revalidatePath("/products");redirect("/products?sampleDeleted=1");}