import { z } from "zod";

const text = z.string().trim().max(10000).optional().transform(v => v || null);
const date = z.string().optional().transform(v => v ? new Date(`${v}T12:00:00.000Z`) : null);
const money = z.string().trim().optional().transform((v, ctx) => { if (!v) return null; const n=Number(v); if(!Number.isFinite(n)||n<0){ctx.addIssue({code:"custom",message:"Enter a valid amount"});return z.NEVER;} return Math.round(n*100); });
const check = z.string().optional().transform(v => v === "on");
export const dealStatuses=["lead","pitched","negotiating","awaiting_contract","contracted","awaiting_product","in_progress","submitted","revisions_requested","approved","awaiting_payment","paid","completed","declined","cancelled"] as const;
export const createBrandDealSchema=z.object({brandName:z.string().trim().min(1).max(200),title:z.string().trim().min(1).max(300),source:z.string().trim().min(1).max(100),dealType:z.string().trim().min(1).max(100)});
export const editBrandDealSchema=z.object({id:z.uuid(),title:z.string().trim().min(1).max(300),contactName:text,contactEmail:z.string().trim().email().optional().or(z.literal("")).transform(v=>v||null),source:z.string().trim().min(1).max(100),dealType:z.string().trim().min(1).max(100),status:z.enum(dealStatuses),priority:z.coerce.number().int().min(0).max(2),startAt:date,dueAt:date,notes:text,fixedCompensationCents:money,giftedValueCents:money,currency:z.string().trim().min(3).max(3),commissionTerms:text,paymentTerms:text,invoiceRequired:check,invoiceNumber:text,invoiceDate:date,paymentDueAt:date,paymentStatus:z.enum(["not_due","expected","overdue","partial","paid"]),amountReceivedCents:money.transform(v=>v??0),receivedAt:date,contractSigned:check,contractSignedAt:date,usageRights:text,organicRights:check,paidUsage:check,exclusivityCategory:text,exclusivityStartAt:date,exclusivityEndAt:date,revisionRounds:z.string().optional().transform(v=>v?Number(v):null).pipe(z.number().int().min(0).nullable()),ownershipNotes:text,disclosures:text,referenceLinks:text});
export const dealDeliverableSchema=z.object({brandDealId:z.uuid(),title:z.string().trim().min(1).max(300),deliverableType:text,platform:text,quantity:z.coerce.number().int().min(1).max(100),dueAt:date,status:z.enum(["not_started","in_progress","submitted","revisions_requested","approved","posted","completed"]),approvalStatus:z.enum(["not_submitted","pending","changes_requested","approved"]),contentId:z.string().optional().transform(v=>v||null).pipe(z.uuid().nullable()),postedAt:date,liveUrl:z.string().url().optional().or(z.literal("")).transform(v=>v||null),notes:text});
export const dealLinkSchema=z.object({brandDealId:z.uuid(),entityType:z.enum(["campaign","product","sample","content"]),entityId:z.uuid()});
