"use server";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { requireOwner } from "@/lib/auth/server";
import { campaignEditSchema, compensationSchema, createCampaignSchema, deliverableSchema, deliverableUpdateSchema, paymentSchema } from "@/lib/campaigns/contracts";
import { addCompensation, addDeliverable, addPayment, archiveCampaign, createCampaign, permanentlyDeleteCampaign, recoverCampaign, updateCampaign, updateDeliverable } from "@/lib/campaigns/repository";
const value=(form:FormData,name:string)=>form.get(name);
export async function createCampaignAction(form:FormData){const owner=await requireOwner();const id=await createCampaign(owner.id,createCampaignSchema.parse({brandName:value(form,"brandName"),name:value(form,"name")}));redirect(`/campaigns/${id}`);}
export async function updateCampaignAction(form:FormData){const owner=await requireOwner();const input=campaignEditSchema.parse({campaignId:value(form,"campaignId"),name:value(form,"name"),status:value(form,"status"),startAt:value(form,"startAt"),dueAt:value(form,"dueAt"),briefReference:value(form,"briefReference"),notes:value(form,"notes")});await updateCampaign(owner.id,input);revalidatePath(`/campaigns/${input.campaignId}`);}
export async function addDeliverableAction(form:FormData){const owner=await requireOwner();const input=deliverableSchema.parse({campaignId:value(form,"campaignId"),title:value(form,"title"),status:value(form,"status"),dueAt:value(form,"dueAt"),requiredPlatform:value(form,"requiredPlatform"),contentId:value(form,"contentId"),newContentIdea:value(form,"newContentIdea"),notes:value(form,"notes")});await addDeliverable(owner.id,input);revalidatePath(`/campaigns/${input.campaignId}`);}
export async function updateDeliverableAction(form:FormData){const owner=await requireOwner();const input=deliverableUpdateSchema.parse({campaignId:value(form,"campaignId"),deliverableId:value(form,"deliverableId"),status:value(form,"status"),contentId:value(form,"contentId")});await updateDeliverable(owner.id,input);revalidatePath(`/campaigns/${input.campaignId}`);}
export async function addCompensationAction(form:FormData){const owner=await requireOwner();const input=compensationSchema.parse({campaignId:value(form,"campaignId"),type:value(form,"type"),amountCents:value(form,"amount"),commissionPercent:value(form,"commissionPercent"),expectedPaymentAt:value(form,"expectedPaymentAt"),notes:value(form,"notes")});await addCompensation(owner.id,input);revalidatePath(`/campaigns/${input.campaignId}`);}
export async function addPaymentAction(form:FormData){const owner=await requireOwner();const input=paymentSchema.parse({campaignId:value(form,"campaignId"),compensationId:value(form,"compensationId"),status:value(form,"status"),amountCents:value(form,"amount"),dueAt:value(form,"dueAt"),receivedAt:value(form,"receivedAt"),paymentReference:value(form,"paymentReference"),notes:value(form,"notes")});await addPayment(owner.id,input);revalidatePath(`/campaigns/${input.campaignId}`);}
export async function archiveCampaignAction(form:FormData){const owner=await requireOwner();await archiveCampaign(owner.id,String(value(form,"campaignId")));revalidatePath("/campaigns");redirect("/campaigns");}
export async function recoverCampaignAction(form:FormData){const owner=await requireOwner();await recoverCampaign(owner.id,String(value(form,"campaignId")));revalidatePath("/campaigns");}
export async function permanentlyDeleteCampaignAction(form:FormData){const owner=await requireOwner();const id=String(value(form,"campaignId"));const result=await permanentlyDeleteCampaign(owner.id,id);if(result.deleted){revalidatePath("/campaigns");redirect("/campaigns?deleted=1");}if(result.reason==="not_found")redirect("/campaigns?deleteError=Campaign%20not%20found");redirect(`/campaigns/${id}?deleteError=${encodeURIComponent(`This campaign contains ${result.blockers?.join(", ")}. Archive it instead.`)}`);}
