import Link from "next/link";
import { requireOwner } from "@/lib/auth/server";
import { listCampaigns } from "@/lib/campaigns/repository";
import { PageHeader } from "@/components/ui/page-header";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/status-badge";
import { createCampaignAction, recoverCampaignAction } from "./actions";
export const dynamic="force-dynamic";
export default async function CampaignsPage({searchParams}:{searchParams:Promise<{archived?:string}>}){const owner=await requireOwner();const archived=(await searchParams).archived==="1";const rows=await listCampaigns(owner.id,archived);return <section className="space-y-8"><PageHeader eyebrow="Campaigns" title="Every deliverable, deadline, and dollar." description="Start with the brand and campaign name. Add commercial details only when you know them."/>{!archived&&<form action={createCampaignAction} className="luxury-card grid gap-4 rounded-xl p-5 md:grid-cols-[1fr_1fr_auto] md:items-end"><Field label="Brand" name="brandName" required placeholder="Brand name"/><Field label="Campaign" name="name" required placeholder="Campaign name"/><button className="primary-action min-h-12 px-6 text-sm font-bold">Create campaign</button></form>}<div className="flex items-center justify-between"><h2 className="display-heading text-3xl">{archived?"Archived campaigns":"Campaign workspace"}</h2><Link className="text-sm font-bold text-[var(--accent-strong)]" href={archived?"/campaigns":"/campaigns?archived=1"}>{archived?"Back to active":"View archive"}</Link></div>{!rows.length?<EmptyState title={archived?"Archive is empty":"No campaigns yet"} description={archived?"Archived campaigns remain recoverable here.":"Brand and campaign name are all you need to begin."}/>:<div className="grid gap-3">{rows.map(({campaign,brandName,progress})=><article key={campaign.id} className="luxury-card flex flex-wrap items-center justify-between gap-4 rounded-xl p-5"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[var(--accent-strong)]">{brandName??"No brand"}</p><h3 className="mt-1 font-bold">{campaign.name}</h3><div className="mt-2 flex flex-wrap gap-3 text-sm text-[var(--muted)]"><StatusBadge>{campaign.status}</StatusBadge><span>{progress.completed}/{progress.total} completed</span>{campaign.dueAt&&<span>Due {campaign.dueAt.toLocaleDateString()}</span>}</div></div>{archived?<form action={recoverCampaignAction}><input type="hidden" name="campaignId" value={campaign.id}/><button className="min-h-11 px-3 text-sm font-bold text-[var(--accent-strong)]">Recover</button></form>:<Link href={`/campaigns/${campaign.id}`} className="primary-action inline-flex min-h-11 items-center px-4 text-sm font-bold">Open</Link>}</article>)}</div>}</section>}
function Field({label,name,...props}:{label:string;name:string;required?:boolean;placeholder?:string}){return <label className="grid gap-2 text-sm font-bold">{label}<input name={name} className="min-h-12 border border-[var(--line)] bg-white px-3 font-normal outline-none focus:border-[var(--accent-strong)]" {...props}/></label>}
