import { archiveAttachmentAction, renameAttachmentAction, restoreAttachmentAction } from "@/lib/attachments/actions";
import { listAttachments } from "@/lib/attachments/repository";
import { SurfaceCard } from "@/components/ui/surface-card";

const size = (bytes: number) => bytes < 1024 * 1024 ? `${Math.ceil(bytes / 1024)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`;

export async function ProductVideoPanel({ ownerUserId, productId, returnTo }: { ownerUserId: string; productId: string; returnTo: string }) {
  const target = { type: "product" as const, id: productId };
  const [active, archived] = await Promise.all([listAttachments(ownerUserId, target, false, "video"), listAttachments(ownerUserId, target, true, "video")]);
  return <SurfaceCard>
    <h2 className="display-heading text-2xl">Reference videos</h2>
    <p className="mt-2 text-sm text-[var(--muted)]">Upload product videos to keep for scripting, filming, and reference. Videos stay private.</p>
    <form action="/api/attachments" method="post" encType="multipart/form-data" className="mt-5 flex flex-wrap items-end gap-3"><input type="hidden" name="targetType" value="product" /><input type="hidden" name="targetId" value={productId} /><input type="hidden" name="returnTo" value={returnTo} /><input type="hidden" name="attachmentKind" value="video" /><label className="grid gap-2 text-sm font-bold">Video<input required type="file" name="file" accept="video/mp4,video/quicktime,video/webm,.mp4,.mov,.webm" className="min-h-12 max-w-full border border-[var(--line)] bg-white px-3 py-2 font-normal" /></label><button className="primary-action min-h-12 px-5 text-sm font-bold">Upload video</button></form>
    <div className="mt-5 grid gap-4">{active.length === 0 ? <p className="text-sm text-[var(--muted)]">No reference videos uploaded yet.</p> : active.map(({ attachment }) => <article key={attachment.id} className="border border-[var(--line)] p-4"><video controls preload="metadata" className="max-h-96 w-full bg-black" src={`/api/attachments/${attachment.id}`} /><div className="mt-3 flex flex-wrap items-start justify-between gap-3"><div><a href={`/api/attachments/${attachment.id}`} target="_blank" rel="noreferrer" className="font-bold text-[var(--accent-strong)]">{attachment.originalFilename}</a><p className="mt-1 text-xs text-[var(--muted)]">Video · {size(attachment.sizeBytes)} · {attachment.createdAt.toLocaleDateString()}</p></div><form action={archiveAttachmentAction}><input type="hidden" name="attachmentId" value={attachment.id} /><input type="hidden" name="returnTo" value={returnTo} /><button className="text-sm font-bold text-[var(--accent-strong)]">Archive</button></form></div><form action={renameAttachmentAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="attachmentId" value={attachment.id} /><input type="hidden" name="returnTo" value={returnTo} /><input required name="name" defaultValue={attachment.originalFilename} className="min-h-11 flex-1 border border-[var(--line)] px-3 text-sm" /><button className="min-h-11 border border-[var(--line)] px-3 text-sm font-bold">Rename</button></form></article>)}</div>
    {archived.length > 0 && <details className="mt-5"><summary className="cursor-pointer text-sm font-bold text-[var(--accent-strong)]">Archived videos ({archived.length})</summary><div className="mt-3 grid gap-2">{archived.map(({ attachment }) => <form key={attachment.id} action={restoreAttachmentAction} className="flex items-center justify-between border border-[var(--line)] p-3"><input type="hidden" name="attachmentId" value={attachment.id} /><input type="hidden" name="returnTo" value={returnTo} /><span className="text-sm">{attachment.originalFilename}</span><button className="text-sm font-bold text-[var(--accent-strong)]">Restore</button></form>)}</div></details>}
  </SurfaceCard>;
}
